### ISSUE TITLE
Trouble getting software package running in windows

### ISSUE THREAD

**Issue by alexs135** [Airspace-Encounter-Models/em-overview#13]
I've been trying to follow the readme to get this running on my machine but every time I try to run bootstrap.sh I get this message. AEM_DIR_CORE is in my PATH as far as I can tell so I'm not sure why I keep getting "AEM_DIR_CORE is unset." I also have Strawberry Perl (which has been added to PATH as well) 
<img width="473" alt="AEMerror" src="https://user-images.githubusercontent.com/127225078/223468484-c781996d-459d-4f9f-a0d9-5aa3928c9b27.PNG">

Not sure if this git repo is still active but any help is appreciated!

**Comment by aweinert-MIT** [comment]
What OS are you using? Windows Subsystem for Linux? MacOS? Native Linux?

**Comment by alexs135** [comment]
Windows Subsystem for Linux

**Comment by aweinert-MIT** [comment]
Are you running `bootstrap.sh` as admin / superuser or through `sudo`? For the latter are you using `sudo -E` to preserve environment variables?

**Comment by alexs135** [comment]
I had mistakenly left out the -E. With that I no longer get the "AEM_DIR_CORE is unset" message but I still get that 'libxml-xpath-perl' has no installation candidate. Trying to run setup.sh afterwards still results in a lot of "no such file or directory" messages

**Comment by aweinert-MIT** [comment]
Are you still getting `Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set)` when running `bootstrap.sh`? That error shouldn't be produced by the script if git is setup correctly.

**Comment by alexs135** [comment]
Yes I'm still getting that error. What should I try to fix that?

**Comment by aweinert-MIT** [comment]
Resolving git and system issues is outside of the scope I can provide technical assistance. Without knowing your system and user configuration, there are many potential issues and I can't diagnose that. I recommend Googling the error and seeing what others have done. To help, here are a few stackoverflow questions that maybe relevant.
https://stackoverflow.com/q/16853624/363829 
https://stackoverflow.com/q/57980690/363829
https://stackoverflow.com/q/7116015/363829

**Comment by alexs135** [comment]
I had a feeling that would be the case. I'll see what I can figure out from here. Regardless, thank you for your help!

**Comment by aweinert-MIT** [comment]
Issue closed because system environment question has been resolved. Issue stemmed from `sudo` and no code update required
